name: flame-moe-a100
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - cmake
  - ninja
  - make
  - pkg-config
  - setuptools
  - wheel
  - numpy=1.26.4
  - pybind11
  - pytorch=2.6.*
  - torchvision=0.21.*
  - torchaudio=2.6.*
  - pytorch-cuda=12.1
  - transformers
  - tensorboard
  - einops
  - flask-restful
  - nltk
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pytest-mock
  - pytest-random-order
  - sentencepiece
  - tiktoken
  - wrapt
  - zarr
  - pip:
      - wandb
      - tensorstore!=0.1.46,!=0.1.72
      - nvidia-modelopt[torch]>=0.19.0
      - nvidia-resiliency-ext
