#!/usr/bin/env bash
# Residual-expert step for one HP-sensitivity cell (post-hoc, router-only).
#
# The cell's own self-generated replay (round_8, i.e. generated by its final
# checkpoint) plus the shared backbone BoS set tune the router; n_residual
# matches the cell's per-task expert count, so the residual group is one
# task-sized group of no-LoRA rows -- 2 / 4 / 8 rows for the 2 x rank32 /
# 4 x rank16 / 8 x rank8 cells, 1 for the rank-64 baseline.
#
#   NAME=e4_r16 GPU=0 bash add_residual.sh
set -uo pipefail
TRACE=/home/seonghyeonnoh/yemokoo/30_flame_agent/LLM-continual-learning/trace
PY=$TRACE/.venv-runtime/bin/python
NAME=${NAME:?cell name, e.g. e4_r16 or order_reverse}
GPU=${GPU:?}
ROOT=${ROOT:-/data2/seonghyeonnoh/paper/hp_sens}
RUN=$ROOT/$NAME
BB=${BB:-/data2/seonghyeonnoh/LLM-continual-learning-runs/trace/residual_router_20260915/data/backbone_bos/records.jsonl}
OUT=${OUT:-$RUN/residual}
say(){ printf '[RES-%s %s] %s\n' "$NAME" "$(date '+%F %T')" "$*" | tee -a "$ROOT/progress.log"; }

[ -f "$RUN/cell.json" ] || { say "no $RUN/cell.json"; exit 1; }
[ -f "$RUN/model/7/lora_moe_meta.json" ] || { say "no round 7 checkpoint"; exit 1; }
[ -f "$BB" ] || { say "no backbone BoS records at $BB"; exit 1; }
NRES=$($PY -c "import json;print(json.load(open('$RUN/cell.json'))['experts_per_task'])")
ORDER=$($PY -c "import json;print(json.load(open('$RUN/cell.json'))['task_order'])")

GR=$RUN/gen/round_8
REPLAY="gen:"
IFS=',' read -r -a TASKS <<< "$ORDER"
for t in "${TASKS[@]}"; do
  f=$GR/$t/records.jsonl
  [ -f "$f" ] || { say "missing self-generated replay for $t ($f) -- rerun run_hp_cell.sh with GEN_FINAL=1"; exit 1; }
  REPLAY+="$t=$f,"
done
REPLAY=${REPLAY%,}

if [ -f "$OUT/router_state.pt" ]; then say "already done -> $OUT"; exit 0; fi
say "train start gpu$GPU n_residual=$NRES"
( cd "$TRACE" && CUDA_VISIBLE_DEVICES=$GPU $PY scripts/residual/train_router_residual.py \
    --source "$RUN/model/7" --replay "$REPLAY" --backbone "$BB" --out "$OUT" \
    --n_residual "$NRES" --replay_per_task 500 --backbone_n 500 \
    --batch 8 --accum 2 --lr 2e-4 --epochs 1 ${XARGS:-} ) \
  > "$RUN/logs/residual.log" 2>&1
rc=$?
[ -f "$OUT/router_state.pt" ] || { say "TRAIN FAILED rc=$rc ($RUN/logs/residual.log)"; exit 1; }
say "train done: $(tail -1 "$OUT/train_log.jsonl" 2>/dev/null)"
